DETECTOR:
  DATASET:
    # .npy数据路径
    BENIGN_DATASET_PATH : "../data/trial_ben.npy"
    MALWARE_DATASET_PATH : "../data/trial_mal.npy"

    # .bmp数据根目录路径
    BENIGN_BMP_DATASET_PATH : "../data/trial_ben.bmp"
    MALWARE_BMP_DATASET_PATH : "../data/trial_mal.bmp"
    # .bmp数据训练集路径
    TRAIN_BENIGN_BMP_DATASET_PATH : "../data/trial_ben.bmp/train"
    TRAIN_MALWARE_BMP_DATASET_PATH : "../data/trial_mal.bmp/train"
    # .bmp数据测试集路径
    TEST_BENIGN_BMP_DATASET_PATH : "../data/trial_ben.bmp/test"
    TEST_MALWARE_BMP_DATASET_PATH : "../data/trial_mal.bmp/test"

  MODEL:
    # ResNet模型的位置
    RESNET_MODEL_PATH : "models/resnet18_epoch18_best.pth"


GAN:
  DATASET:
    # .npy数据路径
    BENIGN_DATASET_PATH : "../data/trial_ben.npy"
    MALWARE_DATASET_PATH : "../data/trial_mal.npy"

    # .bmp数据根目录路径
    BENIGN_BMP_DATASET_PATH : "../data/trial_ben.bmp"
    MALWARE_BMP_DATASET_PATH : "../data/trial_mal.bmp"
    # .bmp数据训练集路径
    TRAIN_BENIGN_BMP_DATASET_PATH : "../data/trial_ben.bmp/train"
    TRAIN_MALWARE_BMP_DATASET_PATH : "../data/trial_mal.bmp/train"
    # .bmp数据测试集路径
    TEST_BENIGN_BMP_DATASET_PATH : "../data/trial_ben.bmp/test"
    TEST_MALWARE_BMP_DATASET_PATH : "../data/trial_mal.bmp/test"

  MODEL:
    # ResNet模型的位置
    RESNET_MODEL_PATH : "../results/resnet18_epoch18_best.pth"
